version: 1

generator:
  # Full TLD list (IANA). If provided, overrides 'tlds' list.
  # Official, frequently updated source:
  # https://data.iana.org/TLD/tlds-alpha-by-domain.txt
  tlds_file: "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
  min_length: 1
  max_length: 20
  alphabet: "abcdefghijklmnopqrstuvwxyz0123456789-"
  allow_hyphen: true
  forbid_leading_hyphen: true
  forbid_trailing_hyphen: true
  forbid_double_hyphen: true

limits:
  concurrency: 1500         # number of concurrent checks
  rate_per_second: 3000     # global RPS limit
  max_candidates: 1000000000   # maximum generated domain names per pass

http_check:
  timeout: "3s"
  retry: 1
  method: "GET"
  body_limit: "32KB"
  accept_status_min: 200
  accept_status_max: 399
  try_https_first: true

run:
  loop: false        # repeat the generation loop when max_candidates is reached